services:
  postgres:
    image: 'timescale/timescaledb:latest-pg16'
    environment:
      - 'POSTGRES_DB=ticker'
      - 'POSTGRES_PASSWORD=ticker'
      - 'POSTGRES_USER=ticker'
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  rabbitmq:
    image: 'rabbitmq:4.0.0-beta.3-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=ticker'
      - 'RABBITMQ_DEFAULT_USER=ticker'
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped
    volumes:
      - 'rabbitmq-data:/var/lib/rabbitmq'

volumes:
  postgres-data:
  rabbitmq-data: