spring:
  application.name: gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: ticker
            uri: http://localhost:8091
            predicates:
              - path=/ticker/**
            filters:
              - StripPrefix=1

server:
  port: 8090

