spring:
  application.name: ticker

  rabbitmq:
    host: localhost
    port: 5672
    username: ticker
    password: ticker

  datasource:
    url: jdbc:postgresql://localhost:5432/ticker
    username: ticker
    password: ticker
    driver-class-name: org.postgresql.Driver

server:
  port: 8091

#logging:
#  level:
#    org.springframework: DEBUG
